// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9lMkxqjII007J-ZYcCsfQxiL7yvplCps',
    appId: '1:730778393142:web:254c8d33e9062eeba11697',
    messagingSenderId: '730778393142',
    projectId: 'kigali-city-services-d3afa',
    authDomain: 'kigali-city-services-d3afa.firebaseapp.com',
    storageBucket: 'kigali-city-services-d3afa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLE3oUdsQnS7nLJGxvbP8BIWaEz7xaCI',
    appId: '1:730778393142:android:df637f20ca68b995a11697',
    messagingSenderId: '730778393142',
    projectId: 'kigali-city-services-d3afa',
    storageBucket: 'kigali-city-services-d3afa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9lMkxqjII007J-ZYcCsfQxiL7yvplCps',
    appId: '1:730778393142:web:cd2fd99199746f2da11697',
    messagingSenderId: '730778393142',
    projectId: 'kigali-city-services-d3afa',
    authDomain: 'kigali-city-services-d3afa.firebaseapp.com',
    storageBucket: 'kigali-city-services-d3afa.firebasestorage.app',
  );
}
